import Head from "next/head";
import Image from "next/image";
import { IBM_Plex_Sans_Condensed, Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
//import places from "../lib/db.json";
import CardList from "../components/CardList";
import Header from "@/components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tourio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <CardList />
      </main>
    </>
  );
}
